curl --data "experiment=INTERFERENCE&role=super&session_token=super&equipment_id=set_0&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=INTERFERENCE&role=super&session_token=super&equipment_id=set_0&device_id=device_1&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=INTERFERENCE&role=super&session_token=super&equipment_id=set_1&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=INTERFERENCE&role=super&session_token=super&equipment_id=set_1&device_id=device_1&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=INTERFERENCE&role=super&session_token=super&equipment_id=set_2&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=INTERFERENCE&role=super&session_token=super&equipment_id=set_2&device_id=device_1&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=BACTERIA_GROWTH&role=super&session_token=super&equipment_id=set_0&device_id=device_0&command=AUTO|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=BACTERIA_GROWTH&role=super&session_token=super&equipment_id=set_1&device_id=device_0&command=AUTO|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=BACTERIA_GROWTH&role=super&session_token=super&equipment_id=set_2&device_id=device_0&command=AUTO|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=BACTERIA_GROWTH&role=super&session_token=super&equipment_id=set_3&device_id=device_0&command=AUTO|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl https://stem-ap.polyu.edu.hk/remotelab/api/health/scan.php
curl --data "experiment=APPARENT_DEPTH&role=super&session_token=super&equipment_id=set_0&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=APPARENT_DEPTH&role=super&session_token=super&equipment_id=set_1&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=APPARENT_DEPTH&role=super&session_token=super&equipment_id=set_2&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=APPARENT_DEPTH&role=super&session_token=super&equipment_id=set_3&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=APPARENT_DEPTH&role=super&session_token=super&equipment_id=set_4&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=APPARENT_DEPTH&role=super&session_token=super&equipment_id=set_5&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=EM_INDUCTION&role=super&session_token=super&equipment_id=set_0&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=EM_INDUCTION&role=super&session_token=super&equipment_id=set_1&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=EM_INDUCTION&role=super&session_token=super&equipment_id=set_2&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=EM_INDUCTION&role=super&session_token=super&equipment_id=set_3&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=VISIBLE_SPECTRUM&role=super&session_token=super&equipment_id=set_0&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=VISIBLE_SPECTRUM&role=super&session_token=super&equipment_id=set_1&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=VISIBLE_SPECTRUM&role=super&session_token=super&equipment_id=set_2&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=VISIBLE_SPECTRUM&role=super&session_token=super&equipment_id=set_3&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=GREEN_HOUSE&role=super&session_token=super&equipment_id=set_0&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=GREEN_HOUSE&role=super&session_token=super&equipment_id=set_1&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=TITRATION&role=super&session_token=super&equipment_id=set_0&device_id=device_0&command=RESTART|1" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php
curl --data "experiment=ULTRASOUND&role=super&session_token=super&equipment_id=set_0&device_id=device_0&command=INIT|0" https://stem-ap.polyu.edu.hk/remotelab/api/experiment/setCommand.php